fix: Disable Google Smart Lock to fix error when, after signing in, existing writing and sent challenges not displaying. Error was: Existing user is able to go to main menu after signing in, but sign in shows: com.firebase.ui.auth.FirebaseUiException: Error when saving credential.         at com.firebase.ui.auth.viewmodel.smartlock.SmartLockHandler$1.onComplete(SmartLockHandler.java:99)
Then any existing writing or sent challenges do not display. Further, submitting practice does not display the writings.
Signing out able to show sign in screen, however logged this error:
2022-05-21 15:07:16.286 8720-8855/? W/Firestore: (23.0.0) [Firestore]: Listen for Query(target=Query(users/mdhsieh8@gmail.com/challenges where senderId == # com.google.firestore.v1.Value@c72942c2
    integer_value: 0
    string_value: "michael.hsieh@sjsu.edu" order by __name__);limitType=LIMIT_TO_FIRST) failed: Status{code=PERMISSION_DENIED, description=Missing or insufficient permissions., cause=null}
2022-05-21 15:07:16.293 8720-8720/? W/MainActivity: listen:error
    com.google.firebase.firestore.FirebaseFirestoreException: PERMISSION_DENIED: Missing or insufficient permissions.
        at com.google.firebase.firestore.util.Util.exceptionFromStatus(Util.java:117)

Possibly related cause, I switched from release to debug variant in order to do some UI testing. This required re-installing the app with pop-up dialog in AS.
After making the UI test, I tried switching to release variant.
Both variants showed the error.
I also cold booted the emulator once because emulator wasn't responding.

I added the SHA-1 debug and Google Play store signing keys into Google Firestore.
This error occurred on both debug and release variants.

Besides fixing this error, I also tried to order writings and challenges by timestamp, but I didn't create an index in Firestore. There were errors and writings and challenges wouldn't display. Commented out ordering for this commit.